create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  retailcrm_id bigint not null,
  external_id text null,
  order_number text null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  status text not null,
  customer_name text not null,
  customer_phone text null,
  customer_email text null,
  city text null,
  total_amount numeric(12, 2) not null default 0,
  currency text not null default 'KZT',
  items_count integer not null default 0,
  raw_payload jsonb not null,
  synced_at timestamptz not null default now(),
  telegram_notified boolean not null default false,
  telegram_notified_at timestamptz null,
  notification_error text null,
  constraint orders_retailcrm_id_key unique (retailcrm_id),
  constraint orders_total_amount_non_negative check (total_amount >= 0),
  constraint orders_items_count_non_negative check (items_count >= 0)
);

create unique index if not exists orders_external_id_unique_idx
  on public.orders (external_id)
  where external_id is not null;

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_updated_at_idx on public.orders (updated_at desc);
create index if not exists orders_synced_at_idx on public.orders (synced_at desc);
create index if not exists orders_telegram_notified_idx on public.orders (telegram_notified);

create or replace function public.claim_order_notification(p_retailcrm_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_claimed boolean := false;
begin
  update public.orders
  set
    notification_error = '__sending__:' || now()::text,
    synced_at = now()
  where retailcrm_id = p_retailcrm_id
    and telegram_notified = false
    and (
      notification_error is null
      or notification_error = ''
      or notification_error not like '__sending__:%'
      or (
        notification_error like '__sending__:%'
        and nullif(replace(notification_error, '__sending__:', ''), '')::timestamptz < now() - interval '15 minutes'
      )
    )
  returning true into v_claimed;

  return coalesce(v_claimed, false);
end;
$$;
